import XCTest

extension EncodingTests {
    static let __allTests = [
        ("testQ1", testQ1),
    ]
}

extension QuestionParsersTestsFull {
    static let __allTests = [
        ("testQ1", testQ1),
        ("testQ10", testQ10),
        ("testQ11", testQ11),
        ("testQ12", testQ12),
        ("testQ13", testQ13),
        ("testQ14", testQ14),
        ("testQ15", testQ15),
        ("testQ16", testQ16),
        ("testQ17", testQ17),
        ("testQ18", testQ18),
        ("testQ19", testQ19),
        ("testQ2", testQ2),
        ("testQ20", testQ20),
        ("testQ21", testQ21),
        ("testQ22", testQ22),
        ("testQ23", testQ23),
        ("testQ24", testQ24),
        ("testQ25", testQ25),
        ("testQ26", testQ26),
        ("testQ27", testQ27),
        ("testQ28", testQ28),
        ("testQ29", testQ29),
        ("testQ3", testQ3),
        ("testQ30", testQ30),
        ("testQ31", testQ31),
        ("testQ32", testQ32),
        ("testQ33", testQ33),
        ("testQ34", testQ34),
        ("testQ35", testQ35),
        ("testQ36", testQ36),
        ("testQ37", testQ37),
        ("testQ38", testQ38),
        ("testQ39", testQ39),
        ("testQ4", testQ4),
        ("testQ40", testQ40),
        ("testQ41", testQ41),
        ("testQ42", testQ42),
        ("testQ43", testQ43),
        ("testQ44", testQ44),
        ("testQ45", testQ45),
        ("testQ46", testQ46),
        ("testQ47", testQ47),
        ("testQ48", testQ48),
        ("testQ49", testQ49),
        ("testQ5", testQ5),
        ("testQ50", testQ50),
        ("testQ51", testQ51),
        ("testQ52", testQ52),
        ("testQ53", testQ53),
        ("testQ54", testQ54),
        ("testQ55", testQ55),
        ("testQ56", testQ56),
        ("testQ57", testQ57),
        ("testQ58", testQ58),
        ("testQ59", testQ59),
        ("testQ6", testQ6),
        ("testQ60", testQ60),
        ("testQ61", testQ61),
        ("testQ62", testQ62),
        ("testQ63", testQ63),
        ("testQ64", testQ64),
        ("testQ65", testQ65),
        ("testQ66", testQ66),
        ("testQ67", testQ67),
        ("testQ68", testQ68),
        ("testQ69", testQ69),
        ("testQ7", testQ7),
        ("testQ70", testQ70),
        ("testQ71", testQ71),
        ("testQ72", testQ72),
        ("testQ73", testQ73),
        ("testQ74", testQ74),
        ("testQ75", testQ75),
        ("testQ76", testQ76),
        ("testQ77", testQ77),
        ("testQ78", testQ78),
        ("testQ79", testQ79),
        ("testQ8", testQ8),
        ("testQ80", testQ80),
        ("testQ81", testQ81),
        ("testQ82", testQ82),
        ("testQ83", testQ83),
        ("testQ84", testQ84),
        ("testQ85", testQ85),
        ("testQ86", testQ86),
        ("testQ87", testQ87),
        ("testQ88", testQ88),
        ("testQ89", testQ89),
        ("testQ9", testQ9),
        ("testQ90", testQ90),
        ("testQ91", testQ91),
        ("testQ92", testQ92),
        ("testQ93", testQ93),
        ("testQ94", testQ94),
        ("testQ95", testQ95),
    ]
}

extension QuestionParsersTestsPartial {
    static let __allTests = [
        ("testCount", testCount),
        ("testFilter", testFilter),
        ("testFilters", testFilters),
        ("testFindListGiveShow", testFindListGiveShow),
        ("testFullQuery", testFullQuery),
        ("testListQuestion", testListQuestion),
        ("testListQuestionStart", testListQuestionStart),
        ("testNamedQuery", testNamedQuery),
        ("testNamedValue", testNamedValue),
        ("testNamedValues", testNamedValues),
        ("testNumericValue", testNumericValue),
        ("testPersonQuestion", testPersonQuestion),
        ("testProperties", testProperties),
        ("testProperty", testProperty),
        ("testQueries", testQueries),
        ("testQueryPossessiveRelationships", testQueryPossessiveRelationships),
        ("testThingQuestion", testThingQuestion),
        ("testWhichWhat", testWhichWhat),
        ("testWhoWhatBe", testWhoWhatBe),
    ]
}

extension QuestionParsersTestsQALD7Test {
    static let __allTests = [
        ("testQ1", testQ1),
        ("testQ10", testQ10),
        ("testQ11", testQ11),
        ("testQ12", testQ12),
        ("testQ13", testQ13),
        ("testQ14", testQ14),
        ("testQ15", testQ15),
        ("testQ16", testQ16),
        ("testQ17", testQ17),
        ("testQ18", testQ18),
        ("testQ19", testQ19),
        ("testQ2", testQ2),
        ("testQ20", testQ20),
        ("testQ21", testQ21),
        ("testQ22", testQ22),
        ("testQ23", testQ23),
        ("testQ24", testQ24),
        ("testQ25", testQ25),
        ("testQ26", testQ26),
        ("testQ27", testQ27),
        ("testQ28", testQ28),
        ("testQ29", testQ29),
        ("testQ3", testQ3),
        ("testQ30", testQ30),
        ("testQ31", testQ31),
        ("testQ32", testQ32),
        ("testQ33", testQ33),
        ("testQ4", testQ4),
        ("testQ5", testQ5),
        ("testQ6", testQ6),
        ("testQ7", testQ7),
        ("testQ8", testQ8),
        ("testQ9", testQ9),
    ]
}

extension QuestionParsersTestsQALD7Train {
    static let __allTests = [
        ("testQ1", testQ1),
        ("testQ10", testQ10),
        ("testQ11", testQ11),
        ("testQ12", testQ12),
        ("testQ13", testQ13),
        ("testQ14", testQ14),
        ("testQ15", testQ15),
        ("testQ16", testQ16),
        ("testQ17", testQ17),
        ("testQ18", testQ18),
        ("testQ19", testQ19),
        ("testQ2", testQ2),
        ("testQ20", testQ20),
        ("testQ21", testQ21),
        ("testQ22", testQ22),
        ("testQ23", testQ23),
        ("testQ24", testQ24),
        ("testQ25", testQ25),
        ("testQ26", testQ26),
        ("testQ27", testQ27),
        ("testQ28", testQ28),
        ("testQ29", testQ29),
        ("testQ3", testQ3),
        ("testQ30", testQ30),
        ("testQ31", testQ31),
        ("testQ32", testQ32),
        ("testQ33", testQ33),
        ("testQ34", testQ34),
        ("testQ35", testQ35),
        ("testQ36", testQ36),
        ("testQ37", testQ37),
        ("testQ38", testQ38),
        ("testQ39", testQ39),
        ("testQ4", testQ4),
        ("testQ40", testQ40),
        ("testQ41", testQ41),
        ("testQ42", testQ42),
        ("testQ43", testQ43),
        ("testQ44", testQ44),
        ("testQ45", testQ45),
        ("testQ46", testQ46),
        ("testQ47", testQ47),
        ("testQ48", testQ48),
        ("testQ49", testQ49),
        ("testQ5", testQ5),
        ("testQ50", testQ50),
        ("testQ51", testQ51),
        ("testQ52", testQ52),
        ("testQ53", testQ53),
        ("testQ54", testQ54),
        ("testQ55", testQ55),
        ("testQ56", testQ56),
        ("testQ57", testQ57),
        ("testQ58", testQ58),
        ("testQ59", testQ59),
        ("testQ6", testQ6),
        ("testQ60", testQ60),
        ("testQ61", testQ61),
        ("testQ62", testQ62),
        ("testQ63", testQ63),
        ("testQ64", testQ64),
        ("testQ65", testQ65),
        ("testQ66", testQ66),
        ("testQ67", testQ67),
        ("testQ68", testQ68),
        ("testQ69", testQ69),
        ("testQ7", testQ7),
        ("testQ70", testQ70),
        ("testQ71", testQ71),
        ("testQ72", testQ72),
        ("testQ73", testQ73),
        ("testQ74", testQ74),
        ("testQ75", testQ75),
        ("testQ76", testQ76),
        ("testQ77", testQ77),
        ("testQ78", testQ78),
        ("testQ79", testQ79),
        ("testQ8", testQ8),
        ("testQ80", testQ80),
        ("testQ9", testQ9),
    ]
}

extension TokenParsersTests {
    static let __allTests = [
        ("testCommaOrAndList", testCommaOrAndList),
    ]
}

extension TokenTests {
    static let __allTests = [
        ("testEncoding", testEncoding),
    ]
}

#if !os(macOS)
public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EncodingTests.__allTests),
        testCase(QuestionParsersTestsFull.__allTests),
        testCase(QuestionParsersTestsPartial.__allTests),
        testCase(QuestionParsersTestsQALD7Test.__allTests),
        testCase(QuestionParsersTestsQALD7Train.__allTests),
        testCase(TokenParsersTests.__allTests),
        testCase(TokenTests.__allTests),
    ]
}
#endif
